# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2024  Jacob Koziej <jacobkoziej@gmail.com>

Import('env')


targets = []

targets += env.PDF('01-matlab-at-a-glance.tex')
env.SideEffect(Glob('_minted-01-matlab-at-a-glance/*'), targets[-1])
env.Depends(targets[-1], SConscript('01-matlab-at-a-glance.d/SConscript'))

targets += env.PDF('02-vectorization.tex')
env.SideEffect(Glob('_minted-02-vectorization/*'), targets[-1])
env.Depends(targets[-1], SConscript('02-vectorization.d/SConscript'))

targets += env.PDF('03-indexing.tex')
env.SideEffect(Glob('_minted-03-indexing/*'), targets[-1])
env.Depends(targets[-1], SConscript('03-indexing.d/SConscript'))

targets += env.PDF('04-functions.tex')
env.SideEffect(Glob('_minted-04-functions/*'), targets[-1])
env.Depends(targets[-1], SConscript('04-functions.d/SConscript'))

targets += env.PDF('05-plotting.tex')


Return('targets')
