# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2024  Jacob Koziej <jacobkoziej@gmail.com>

Import('env')


targets = []

targets += env.PDF('01-matlab-at-a-glance.tex')


Return('targets')
