# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2024  Jacob Koziej <jacobkoziej@gmail.com>

Import('env')


targets = []

targets += env.Substfile(
    'git-hash.tex.in',
    SUBST_DICT={
        '@GIT_DIRTY@': env['GIT_DIRTY'],
        '@GIT_HASH@': env['GIT_HASH'],
        '@GIT_HASH_LONG@': env['GIT_HASH_LONG'],
    },
)

targets += env.PDF('submissions.tex')
env.SideEffect(Glob('_minted-submissions/*.pygstyle'), targets[-1])
env.SideEffect(Glob('_minted-submissions/*.pygtex'), targets[-1])

targets += env.PDF('syllabus.tex')


Return('targets')
